### ISSUE TITLE
get_peaks

### ISSUE THREAD

**Issue by jason111o** [guilt/pyaudio-square#1]
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    peaks = list(get_peaks(data))
  File "main.py", line 75, in get_peaks
    while samples[i] * sign > peak_threshold:
IndexError: list index out of range

**Comment by guilt** [comment]
I don't even have that device with me right now to test! 

Looking at it, quite wierd, because `i` is checked before we get into the loop in `get_peaks`. Could you poke around a bit and figure why it happens - and raise a PR? Would be happy to merge it 👍

**Comment by jason111o** [comment]
I have two square up card readers. The older one seems to work when I slide it at the right speed ;)
The newer one on the other hand, it doesn't seem to work at all. I have ported this to python 3 and updated all dependencies to match. Pretty new to PR, but will try and get that uploaded.

**Comment by guilt** [comment]
Sweet. I usually use six if I need to fix it up, will review and get this in! Thank you!
